I might just have all the Travis builds building and passing their tests now. Fingers crossed. GCC won't build locally anymore, which is why I started investigating. Still doesn't build locally (no more "-lclang not found" or whatever but still fails with lots of "undefined reference to [some libclang function]", kinda odd but I don't really care, I usually just build with clang and let Travis do the heavy testing anyway. Also, writing all these commit messages has made me realize just how much I appreciate my IBM Model M mechanical keyboard (over 20 years old and still going, built like a tank).